### ISSUE TITLE
How can content be added, and stay centered?

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/htmlslyde#2]

**Comment by r0hit-gupta** [comment]
Can you please provide more info on the issue ?

**Comment by shakeelmohamed** [comment]
@r0hit-gupta if you look at `index.html` and `styles.css`, every time we need to add a new "slide" we have to hardcode the new `<div>` and accompanying CSS rule. Ideally, the CSS rules should be dynamic

**Comment by Nitiquita** [comment]
@shakeelmohamed, I'm going to try adding some jQuery to make the CSS more dynamic. How would you like the rules to work? Do you want separate rules for each type of action, for example slide bottom, slide right, etc. and then have those rules apply to different div ids?

**Comment by shakeelmohamed** [comment]
@Nitiquita thanks for your interest! The purpose of this project was to use absolutely no JavaScript, so bringing in jQuery won't help out here 😄 

Feel free to send a PR for updating the README with that note

**Comment by Nitiquita** [comment]
I see! Yes, I can update the README. It is a fun project!

**Comment by jokari** [comment]
#7

**Comment by shakeelmohamed** [comment]
Finished with #7
